// src/screens/SettingsScreen.tsx

import { View, Text, ScrollView, TouchableOpacity, Alert } from 'react-native';
import { useState } from 'react';
import tw from '../lib/tailwind';
import { useTranslation } from '../hooks/useTranslation';
import { useTheme } from '../contexts/ThemeContext';
import { Globe, Download, Info, Check, Moon, Sun, Monitor, Palette, Trash2, Database, RefreshCw, LogOut, ChevronRight } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { cleanupAutoGeneratedExpenses, cleanupDuplicateIncomes, cleanupDuplicateRecurringIncomes, getDatabaseStats, resetAllData, resetEverything } from '../database/cleanup';
import { useBudgetStore } from '../store';
import { useAuthContext } from '../contexts/AuthContext';

const LANGUAGES = [
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
];

export const SettingsScreen = ({ navigation }: any) => {
  const { t, locale, changeLanguage } = useTranslation();
  const { isDark, colors, themeMode, setThemeMode, palette } = useTheme();
  const { refresh } = useBudgetStore();
  const { user, signOut } = useAuthContext();
  const [selectedLanguage, setSelectedLanguage] = useState(locale);
  const [signingOut, setSigningOut] = useState(false);

  const handleLanguageChange = async (langCode: string) => {
    try {
      await changeLanguage(langCode);
      setSelectedLanguage(langCode);
      refresh();
    } catch (error) {
      console.error('Failed to change language:', error);
    }
  };

  const handleExportData = () => {
    Alert.alert(t('settings.export'), t('settings.exportMessage'));
  };

  const handleResetAll = () => {
    Alert.alert(t('settings.resetAll'), t('settings.resetAllMessage'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('settings.resetAll'),
        style: 'destructive',
        onPress: () => {
          resetAllData();
          refresh();
          Alert.alert(t('success'), t('settings.resetSuccess'));
        },
      },
    ]);
  };

  const handleCleanupDuplicateIncomes = () => {
    Alert.alert(t('settings.cleanupDuplicates'), t('settings.cleanupDuplicatesMessage'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('settings.cleanup'),
        onPress: () => {
          const removed = cleanupDuplicateIncomes();
          refresh();
          Alert.alert(t('success'), `${removed} ${t('settings.duplicatesRemoved')}`);
        },
      },
    ]);
  };

  const handleCleanupAutoExpenses = () => {
    Alert.alert(t('settings.cleanupAuto'), t('settings.cleanupAutoMessage'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('settings.cleanup'),
        onPress: () => {
          const removed = cleanupAutoGeneratedExpenses();
          refresh();
          Alert.alert(t('success'), `${removed} ${t('settings.autoExpensesRemoved')}`);
        },
      },
    ]);
  };

  const handleCleanupRecurringDuplicates = () => {
    Alert.alert(t('settings.cleanupRecurring'), t('settings.cleanupRecurringMessage'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('settings.cleanup'),
        onPress: () => {
          const removed = cleanupDuplicateRecurringIncomes();
          refresh();
          Alert.alert(t('success'), `${removed} ${t('settings.recurringRemoved')}`);
        },
      },
    ]);
  };

  const handleShowDatabaseStats = () => {
    const stats = getDatabaseStats();
    Alert.alert(
      t('settings.databaseStats'),
      `${t('settings.incomes')}: ${stats.incomes}\n${t('settings.expenses')}: ${stats.expenses}\n${t('settings.recurring')}: ${stats.recurringExpenses}\n${t('settings.categories')}: ${
        stats.categories
      }`
    );
  };

  const handleResetEverything = () => {
    Alert.alert(t('settings.deleteEverything'), t('settings.deleteEverythingMessage'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('settings.deleteAll'),
        style: 'destructive',
        onPress: () => {
          Alert.alert(t('settings.areYouSure'), t('settings.reallyDeleteEverything'), [
            { text: t('cancel'), style: 'cancel' },
            {
              text: t('settings.yesDelete'),
              style: 'destructive',
              onPress: () => {
                resetEverything();
                refresh();
                Alert.alert(t('success'), t('settings.everythingDeleted'));
              },
            },
          ]);
        },
      },
    ]);
  };

  const handleSignOut = async () => {
    Alert.alert(t('settings.signOut'), t('settings.signOutMessage'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('settings.signOut'),
        style: 'destructive',
        onPress: async () => {
          try {
            setSigningOut(true);
            await signOut();
          } catch (error) {
            Alert.alert(t('error'), t('settings.signOutError'));
          } finally {
            setSigningOut(false);
          }
        },
      },
    ]);
  };

  const getThemeLabel = (mode: 'light' | 'dark' | 'system') => {
    return t(`settings.theme.${mode}`);
  };

  const getPaletteName = () => {
    return t(`settings.palettes.${palette}.name`);
  };

  return (
    <View style={tw.style('flex-1', `bg-[${isDark ? colors.dark.bg : colors.light.bg}]`)}>
      <SafeAreaView edges={['top']} style={tw`flex-1`}>
        <ScrollView style={tw`flex-1`} contentContainerStyle={tw`pb-6`}>
          {/* Header */}
          <View style={tw`px-6 pt-4 pb-6`}>
            <Text style={tw.style('text-3xl font-bold', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.title')}</Text>
          </View>

          {/* Color Palette Section */}
          <View style={tw`px-6 mb-8`}>
            <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.colorPalette')}</Text>

            <TouchableOpacity
              onPress={() => navigation.navigate('ThemePalette')}
              style={tw.style('rounded-2xl overflow-hidden flex-row items-center px-4 py-4', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}
            >
              <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                <Palette size={20} color={colors.primary} strokeWidth={2.5} />
              </View>

              <View style={tw`flex-1`}>
                <Text style={tw.style('text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{getPaletteName()}</Text>
              </View>

              <ChevronRight size={20} color={isDark ? colors.dark.textTertiary : colors.light.textTertiary} strokeWidth={2} />
            </TouchableOpacity>
          </View>

          {/* Appearance Section */}
          <View style={tw`px-6 mb-8`}>
            <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.appearance')}</Text>

            <View style={tw.style('rounded-2xl overflow-hidden', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}>
              {(['light', 'dark', 'system'] as const).map((mode, index) => {
                const isSelected = themeMode === mode;
                const isLast = index === 2;
                const IconComponent = mode === 'light' ? Sun : mode === 'dark' ? Moon : Monitor;

                return (
                  <TouchableOpacity
                    key={mode}
                    onPress={() => setThemeMode(mode)}
                    style={tw.style('flex-row items-center px-4 py-4', !isLast && `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}
                  >
                    <View
                      style={tw.style(
                        'w-11 h-11 rounded-xl items-center justify-center mr-4',
                        isSelected ? `bg-[${colors.primary}]/15` : isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`
                      )}
                    >
                      <IconComponent size={20} color={isSelected ? colors.primary : isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                    </View>

                    <Text style={tw.style('flex-1 text-base font-medium', isSelected ? `text-[${colors.primary}]` : `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>
                      {getThemeLabel(mode)}
                    </Text>

                    {isSelected && <Check size={20} color={colors.primary} strokeWidth={2.5} />}
                  </TouchableOpacity>
                );
              })}
            </View>
          </View>

          {/* Language Section */}
          <View style={tw`px-6 mb-8`}>
            <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.language')}</Text>

            <View style={tw.style('rounded-2xl overflow-hidden', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}>
              {LANGUAGES.map((lang, index) => {
                const isSelected = selectedLanguage === lang.code;
                const isLast = index === LANGUAGES.length - 1;

                return (
                  <TouchableOpacity
                    key={lang.code}
                    onPress={() => handleLanguageChange(lang.code)}
                    style={tw.style('flex-row items-center px-4 py-4', !isLast && `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}
                  >
                    <View
                      style={tw.style(
                        'w-11 h-11 rounded-xl items-center justify-center mr-4',
                        isSelected ? `bg-[${colors.primary}]/15` : isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`
                      )}
                    >
                      <Globe size={20} color={isSelected ? colors.primary : isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                    </View>

                    <Text style={tw.style('flex-1 text-base font-medium', isSelected ? `text-[${colors.primary}]` : `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>
                      <Text>{lang.flag}</Text>
                      <Text> {lang.label}</Text>
                    </Text>

                    {isSelected && <Check size={20} color={colors.primary} strokeWidth={2.5} />}
                  </TouchableOpacity>
                );
              })}
            </View>
          </View>

          {/* Data Section */}
          <View style={tw`px-6 mb-8`}>
            <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.data')}</Text>

            <View style={tw.style('rounded-2xl overflow-hidden', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}>
              <TouchableOpacity onPress={handleExportData} style={tw`flex-row items-center px-4 py-4`}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <Download size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>

                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.export')}</Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Developer Tools Section */}
          <View style={tw`px-6 mb-8`}>
            <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.devTools')}</Text>

            <View style={tw.style('rounded-2xl overflow-hidden', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}>
              <TouchableOpacity onPress={handleShowDatabaseStats} style={tw.style('flex-row items-center px-4 py-4', `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <Database size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>
                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.databaseStats')}</Text>
              </TouchableOpacity>

              <TouchableOpacity onPress={handleCleanupDuplicateIncomes} style={tw.style('flex-row items-center px-4 py-4', `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <RefreshCw size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>
                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.cleanupDuplicates')}</Text>
              </TouchableOpacity>

              <TouchableOpacity onPress={handleCleanupAutoExpenses} style={tw.style('flex-row items-center px-4 py-4', `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <RefreshCw size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>
                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.cleanupAuto')}</Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={handleCleanupRecurringDuplicates}
                style={tw.style('flex-row items-center px-4 py-4', `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}
              >
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <RefreshCw size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>
                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.cleanupRecurring')}</Text>
              </TouchableOpacity>

              <TouchableOpacity onPress={handleResetAll} style={tw.style('flex-row items-center px-4 py-4', `border-b border-[${isDark ? colors.dark.border : colors.light.border}]`)}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <Trash2 size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>
                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.resetAll')}</Text>
              </TouchableOpacity>

              <TouchableOpacity onPress={handleResetEverything} style={tw`flex-row items-center px-4 py-4`}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', `bg-red-500/10`)}>
                  <Trash2 size={20} color="#EF4444" strokeWidth={2.5} />
                </View>
                <Text style={tw`flex-1 text-base font-medium text-red-500`}>{t('settings.deleteEverything')}</Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Account Section */}
          {user && (
            <View style={tw`px-6 mb-8`}>
              <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.account')}</Text>

              <View style={tw.style('rounded-2xl overflow-hidden', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}>
                <TouchableOpacity onPress={handleSignOut} disabled={signingOut} style={tw`flex-row items-center px-4 py-4`}>
                  <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', `bg-red-500/10`)}>
                    <LogOut size={20} color="#EF4444" strokeWidth={2.5} />
                  </View>
                  <Text style={tw`flex-1 text-base font-medium text-red-500`}>{signingOut ? <Text>{t('settings.signingOut')}</Text> : <Text>{t('settings.signOut')}</Text>}</Text>
                </TouchableOpacity>
              </View>
            </View>
          )}

          {/* About Section */}
          <View style={tw`px-6 mb-8`}>
            <Text style={tw.style('text-sm font-semibold uppercase tracking-wider mb-4', `text-[${isDark ? colors.dark.textTertiary : colors.light.textTertiary}]`)}>{t('settings.about')}</Text>

            <View style={tw.style('rounded-2xl overflow-hidden', isDark ? `bg-[${colors.dark.card}] border border-[${colors.dark.border}]` : 'bg-white shadow-sm')}>
              <TouchableOpacity onPress={() => Alert.alert('Luma', t('settings.aboutMessage'))} style={tw`flex-row items-center px-4 py-4`}>
                <View style={tw.style('w-11 h-11 rounded-xl items-center justify-center mr-4', isDark ? `bg-[${colors.dark.surface}]` : `bg-[${colors.light.bg}]`)}>
                  <Info size={20} color={isDark ? colors.dark.textSecondary : colors.light.textSecondary} strokeWidth={2.5} />
                </View>

                <Text style={tw.style('flex-1 text-base font-medium', `text-[${isDark ? colors.dark.textPrimary : colors.light.textPrimary}]`)}>{t('settings.about')}</Text>
              </TouchableOpacity>
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
};
