import { db } from './index';

/**
 * ⚠️ HELPER TEMPORAIRE DE DEBUG
 * Supprime toutes les dépenses auto-générées par l'ancien système de recurring
 */
export const cleanupAutoGeneratedExpenses = (): number => {
  try {
    // Supprimer toutes les dépenses créées automatiquement
    const result = db.runSync(`DELETE FROM expenses WHERE id LIKE 'expense-recurring-%'`);

    return result.changes;
  } catch (error) {
    console.error('Cleanup error:', error);
    return 0;
  }
};

/**
 * Reset complet de toutes les données (budgets + expenses)
 */
export const resetAllData = (): void => {
  try {
    db.execSync('DELETE FROM expenses');
    db.execSync('DELETE FROM budgets');
    console.log('✅ All data reset');
  } catch (error) {
    console.error('Reset error:', error);
  }
};

/**
 * Statistiques de la base
 */
export const getDatabaseStats = (): {
  totalExpenses: number;
  autoGeneratedExpenses: number;
  budgets: number;
  recurringExpenses: number;
} => {
  const totalExpenses = db.getFirstSync<{ count: number }>('SELECT COUNT(*) as count FROM expenses')?.count || 0;

  const autoGeneratedExpenses = db.getFirstSync<{ count: number }>(`SELECT COUNT(*) as count FROM expenses WHERE id LIKE 'expense-recurring-%'`)?.count || 0;

  const budgets = db.getFirstSync<{ count: number }>('SELECT COUNT(*) as count FROM budgets')?.count || 0;

  const recurringExpenses = db.getFirstSync<{ count: number }>('SELECT COUNT(*) as count FROM recurring_expenses')?.count || 0;

  return {
    totalExpenses,
    autoGeneratedExpenses,
    budgets,
    recurringExpenses,
  };
};
